---
env:
  jest: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/typescript
  - plugin:jest/recommended
  - plugin:jest/style
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  sourceType: module
plugins:
  - '@typescript-eslint/eslint-plugin'
  - prettier
  - import
  - jest
root: true
rules:
  '@typescript-eslint/await-thenable': error
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-member-accessibility': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/indent': 'off'
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/member-delimiter-style': 'off'
  '@typescript-eslint/member-ordering': error
  '@typescript-eslint/no-confusing-non-null-assertion': error
  '@typescript-eslint/no-empty-function': 'off'
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/no-explicit-any': error
  '@typescript-eslint/no-extra-non-null-assertion': error
  '@typescript-eslint/no-floating-promises':
    - error
    - ignoreVoid: true
  '@typescript-eslint/no-non-null-assertion': error
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
  '@typescript-eslint/no-use-before-define': 'off'
  '@typescript-eslint/no-var-requires': 'off'
  '@typescript-eslint/switch-exhaustiveness-check': error
  array-bracket-newline:
    - error
    - consistent
  array-bracket-spacing:
    - error
    - never
  array-callback-return: error
  block-spacing:
    - error
  brace-style: error
  camelcase:
    - 'off'
    - properties: never
  complexity: error
  computed-property-spacing:
    - error
    - never
  curly:
    - error
    - all
  default-case: 'off'
  default-case-last: 'off'
  dot-location:
    - error
    - property
  dot-notation: error
  eol-last: error
  eqeqeq: error
  func-call-spacing:
    - error
    - never
  func-style: error
  import/no-unresolved: 'off'
  import/order:
    - error
    - alphabetize:
        order: asc
      groups:
        - builtin
        - external
        - internal
        - - parent
          - sibling
          - index
      newlines-between: always
      pathGroups:
        - group: external
          pattern: '@nestjs/**'
        - group: internal
          pattern: '{@tests/**,@type/**,@modules/**,@database/**,@decorators/**,@filters/**,@pipes/**}'
          position: before
      pathGroupsExcludedImportTypes:
        - builtin
  jest/expect-expect:
    - error
    - assertFunctionNames:
        - expect
        - request.**.expect
  jest/no-conditional-expect: 'off'
  key-spacing: error
  keyword-spacing: error
  lines-between-class-members: error
  newline-per-chained-call: 'off'
  no-console:
    - error
    - allow:
        - warn
        - error
  no-dupe-keys: error
  no-else-return: error
  no-implicit-coercion: error
  no-invalid-this: error
  no-lonely-if: error
  no-multi-spaces: error
  no-return-await: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-useless-return: error
  prefer-arrow-callback:
    - error
  prefer-const: error
  prettier/prettier:
    - error
  template-curly-spacing:
    - error
    - never
  valid-typeof: error